### ISSUE TITLE
ченжлоги

### ISSUE THREAD

**Issue by gizeasy** [gpn-prototypes/ui-kit#103]
- автоформирование чейнджлогов с помощью github-release-notes (gren)
- запланировать написать доки для контрибьютеров и для пользователей
- запланировать покрытие текущих компонентов документацией
- включить шаг документирования в процесс создания новых компонентов

**Comment by daynin** [comment]
пример экшена для формирования ченжлогов

```yaml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: |
        yarn policies set-version 1.19.1
        yarn
    - name: Install github-release-notes and generate changelog
      run: |
        npx github-release-notes@0.17.1 changelog --generate --override --token=${{ secrets.GITHUB_TOKEN }} --changelog-filename=TEMP_CHANGELOG.md -B
      env:
        CI: true
    - name: Create and publish realese
      uses: ncipollo/release-action@v1
      with:
        bodyFile: 'TEMP_CHANGELOG.md'
        token: ${{ secrets.GITHUB_TOKEN }}
```
